---
- name: System Update for Debian/Ubuntu
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: System Update for RHEL/CentOS/Rocky/Alma
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: System Update for Windows
  win_updates:
    category_uploaded: ['SecurityUpdates', 'CriticalUpdates', 'Updates']
    state: installed
  when: ansible_os_family == "Windows"
