---
- name: Cisco Firmware Update Workflow
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Run Pre-Upgrade Checks
      include_role:
        name: cisco_pre_check

    - name: Execute Firmware Upgrade (Verified Playbook)
      include_role:
        name: cisco_firmware_updates

    - name: Run Post-Upgrade Checks
      include_role:
        name: cisco_post_check
